import type { Metadata } from "next";
import { Geist, Geist_Mono, Caudex } from "next/font/google";
import "./globals.css";

const caudexSans = Caudex({
  weight: "400",
  subsets: ["latin", "greek"],
  variable: "--font-sans"
})

const caudexSansBold = Caudex({
  weight: "700",
  subsets: ["latin", "greek"],
  variable: "--font-sans-bold"
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${caudexSans.variable} ${caudexSansBold.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
